version: '3'

services:
  db:
    container_name: aquila_pgdb
    restart: always
    image: postgres:13-alpine
    env_file:
      - ./backend/env/postgres.env
    networks:
      - core
    # ports:
    #   - 5432:5432
    volumes:
      - ./backend/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  backend:
    container_name: aquila_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/env/prod.env
    volumes:
      - ./backend:/app/backend
      - /var/run/docker.sock:/var/run/docker.sock
      - static:/app/backend/static
    # ports:
    #   - 8000:8000
    networks:
      - core
    links:
      - db:db
  webapp:
    container_name: aquila_webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    networks:
      - core
    volumes:
      - ./webapp:/app
      - /app/node_modules
      - /app/.next
    # ports:
    #   - 3000:3000
    links:
      - backend:backend
  nginx:
    container_name: aquila_nginx
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/app/backend/static
    ports:
      - 80:80
    links: 
      - backend
      - webapp
    networks:
      - core

networks:
  core:

volumes:
  node-modules:
  static:
