image: python:3.9-alpine

services:
  - postgres:12.2-alpine

stages:
  - "test"

variables:
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apk add --no-cache --virtual .build-deps ca-certificates gcc postgresql-dev linux-headers musl-dev libffi-dev jpeg-dev zlib-dev
  - pip install --upgrade pip
  - pip install -r requirements.txt

# migrations:
#   stage: build
#   script:
#     - python3 manage.py makemigrations
#     # - python3 manage.py makemigrations myapp
#     - python3 manage.py migrate
#     - python3 manage.py check

django-tests:
  stage: test
  script:
    # The MYSQL user only gets permissions for MYSQL_DB, so Django can't create a test database.
    # - echo "GRANT ALL on *.* to '${MYSQL_USER}';"| mysql -u root --password="${MYSQL_ROOT_PASSWORD}" -h mysql
    # use python3 explicitly. see https://wiki.ubuntu.com/Python/3
    - python3 manage.py test

