image: python:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apk update && apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo postgresql-dev jpeg-dev zlib-dev libxml2  libxml2-dev libxslt-dev build-base
  - pip install -r requirements.txt

test:
  script:
    - python manage.py test
